name: Backend Server CI

on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**

env:
  AZURE_APP_NAME: impactly
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: backend
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://${{ env.AZURE_APP_NAME }}.azurewebsites.net

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: backend
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9763C07F1E144125BAB2D4C6589208EC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_88F0377570D141E99139D975E0093F03 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_887AAAA8A994488F805FBF125D62B9E5 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_APP_NAME }}
          package: backend

          












